# wjdlz/NOTE: ci@1.0.5-final-check
name: POC

on:
  push:
    branches: [feat/npm]

concurrency:
  group: main-poc-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# timeout-minutes: 10

permissions:
  contents: write
  pull-requests: write
  # packages: write

env:
  REPO: ${{ github.repository || 'vezham/heroui' }} # inputs.GIT_REPO
  BRANCH: ${{ github.ref_name || 'feat/npm' }} # inputs.GIT_BRANCH

jobs:
  npm-auth:
    runs-on: ubuntu-latest
    
    steps:
      - name: action | checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: vezham/v0xFE-deployer/.github/actions/common/setup-checkout@timeline
        with:
          GIT_REPO: ${{ env.REPO }}
          GIT_BRANCH: ${{ env.BRANCH }}

      - name: action | node & pnpm
        uses: vezham/v0xFE-deployer/.github/actions/common/setup-install-npm@timeline
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: action | changesets/NPM-release
        uses: vezham/v0xFE-deployer/.github/actions/common/changesets-release@timeline
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # - name: fork | v:ci:publish-pre
      #   run: pnpm v:ci:publish-pre